#!/bin/bash

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop the service
        if systemctl is-active --quiet apc-ups-monitor.service; then
            systemctl stop apc-ups-monitor.service
        fi
        
        # Disable the service
        if systemctl is-enabled --quiet apc-ups-monitor.service; then
            systemctl disable apc-ups-monitor.service
        fi
        ;;
    
    failed-upgrade)
        ;;
    
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0