#!/bin/bash
set -e

# UPS Monitor Service Installation Script
# This script installs and configures the UPS Monitor systemd service

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"

echo "Installing UPS Monitor Service..."

# Setup sudo permissions for UPS Monitor operations first
echo "Setting up sudo permissions for configuration management..."
"$SCRIPT_DIR/setup-sudo-permissions.sh"

# Create apc-ups-monitor user if it doesn't exist
if ! getent passwd apc-ups-monitor >/dev/null 2>&1; then
    echo "Creating apc-ups-monitor user..."
    useradd --system --home /var/lib/apc-ups-monitor --create-home \
        --shell /bin/false --comment "UPS Monitor Service" apc-ups-monitor
fi

# Create required directories
echo "Creating directories..."
mkdir -p /var/lib/apc-ups-monitor
mkdir -p /var/log/apc-ups-monitor
mkdir -p /etc/apc-ups-monitor

# Set ownership and permissions
chown apc-ups-monitor:apc-ups-monitor /var/lib/apc-ups-monitor
chown apc-ups-monitor:apc-ups-monitor /var/log/apc-ups-monitor
chown apc-ups-monitor:apc-ups-monitor /etc/apc-ups-monitor
chmod 755 /var/lib/apc-ups-monitor
chmod 755 /var/log/apc-ups-monitor
chmod 755 /etc/apc-ups-monitor

# Install systemd service file
if [ -f "$PACKAGE_DIR/systemd/apc-ups-monitor.service" ]; then
    echo "Installing systemd service..."
    cp "$PACKAGE_DIR/systemd/apc-ups-monitor.service" /etc/systemd/system/
    chmod 644 /etc/systemd/system/apc-ups-monitor.service
else
    echo "Error: systemd service file not found at $PACKAGE_DIR/systemd/apc-ups-monitor.service"
    exit 1
fi

# Create default configuration
if [ ! -f /etc/apc-ups-monitor/config.conf ]; then
    echo "Creating default configuration..."
    cat > /etc/apc-ups-monitor/config.conf << 'EOF'
# UPS Monitor Configuration
[DEFAULT]
host = 0.0.0.0
port = 8555
debug = false
log_level = INFO
db_path = /var/lib/apc-ups-monitor/ups_monitoring.db

[database]
# Database connection pool settings
pool_size = 5
cache_timeout = 30
monitor_interval = 5
batch_size = 100

[monitoring]
# UPS monitoring settings
use_mock_data = false
apcaccess_timeout = 5
websocket_emit_interval = 2

[apcupsd]
# apcupsd configuration
auto_configure = true
auto_detect_devices = true
config_backup = true
EOF
    chown apc-ups-monitor:apc-ups-monitor /etc/apc-ups-monitor/config.conf
    chmod 644 /etc/apc-ups-monitor/config.conf
fi

# Reload systemd and enable service
echo "Enabling systemd service..."
systemctl daemon-reload
systemctl enable apc-ups-monitor.service

# Check if apcupsd is installed and configure if needed
if command -v apcupsd >/dev/null 2>&1; then
    echo "Found apcupsd, checking configuration..."
    if [ ! -f /etc/default/apcupsd ] || ! grep -q "ISCONFIGURED=yes" /etc/default/apcupsd 2>/dev/null; then
        echo "Configuring apcupsd..."
        
        # Enable apcupsd
        echo "ISCONFIGURED=yes" > /etc/default/apcupsd
        
        # Create basic configuration if needed
        if [ ! -f /etc/apcupsd/apcupsd.conf ]; then
            cat > /etc/apcupsd/apcupsd.conf << 'EOF'
# apcupsd.conf v1.1
# Generated by UPS Monitor

# UPS Identification
#UPSNAME
UPSCABLE usb
UPSTYPE usb
#DEVICE

# System Settings
LOCKFILE /var/lock
SCRIPTDIR /etc/apcupsd
PWRFAILDIR /etc/apcupsd
NOLOGINDIR /etc

# Power Management
ONBATTERYDELAY 6
BATTERYLEVEL 5
MINUTES 3
TIMEOUT 0
ANNOY 300
ANNOYDELAY 60
NOLOGON disable
KILLDELAY 0

# Network Settings
NETSERVER on
NISIP 127.0.0.1
NISPORT 3551

# Logging
EVENTSFILE /var/log/apcupsd.events
EVENTSFILEMAX 10
STATFILE /var/log/apcupsd.status
LOGSTATS off

# Advanced
UPSCLASS standalone
UPSMODE disable
STATTIME 0
DATATIME 0
EOF
        fi
        
        # Enable and start apcupsd
        systemctl daemon-reload
        systemctl enable apcupsd
        if systemctl start apcupsd; then
            echo "apcupsd started successfully"
        else
            echo "Warning: Failed to start apcupsd. You may need to configure it manually."
        fi
    else
        echo "apcupsd already configured"
    fi
else
    echo "apcupsd not found. Install it with: apt-get install apcupsd"
fi

# Start the UPS Monitor service
echo "Starting UPS Monitor service..."
if systemctl start apc-ups-monitor.service; then
    echo "UPS Monitor service started successfully!"
    systemctl status apc-ups-monitor.service --no-pager -l
else
    echo "Warning: Failed to start UPS Monitor service. Check logs with: journalctl -u apc-ups-monitor.service"
fi

echo ""
echo "Installation complete!"
echo "Service is running on http://0.0.0.0:8555"
echo "You can check the service status with: systemctl status apc-ups-monitor"
echo "View logs with: journalctl -u apc-ups-monitor -f"